### ISSUE TITLE
Profile views increment on visiting other links as well

### ISSUE THREAD

**Issue by harshita130602** [antonkomarev/github-profile-views-counter#20]
The profile views are incrementing when a person himself/herself visit their own profile. Even apart from that, the profile views are incrementing when you are opening any other link on your account like explore, issues etc. So basically, everytime when you click on your mouse to visit any link on github, the views are incrementing. I think, they should only increment when someone visit the profile only.

**Comment by antonkomarev** [comment]
Hi @harshita130602!
Are you sure that counter is incrementing on explore & issues pages? I've tested it right now and it doesn't.
About incrementing counter on visiting own profile you are totally right, it's incrementing because GitHub protects your private data (Username, IP address & UserAgent), so there is no way to track who has viewed profile page. And there is no way to get unique visitors count, that's why this counter is dead simple and just increment count on any hit.

**Comment by antonkomarev** [comment]
Maybe you have browser plugins which are getting info from your GitHub profile or something like that?

**Comment by harshita130602** [comment]
Sorry, my bad! Not every link. But, if we navigate any link on our own profile then it's incrementing like if I open my profile then let the views be x, after navigating "repositories" section and then coming back to the profile, the views will become x+2. I think, this shouldn't be the matter.

**Comment by antonkomarev** [comment]
When you opening your profile page your counter increments, when you are opening a repository with your profile https://github.com/harshita130602/harshita130602 your counter increments as well because it increments every time it was rendered in the browser. It is behaving like anonymous tracking pixel. I've covered more details in the [FAQ section](https://github.com/antonkomarev/github-profile-views-counter#faq).

**Comment by antonkomarev** [comment]
Duplicate threads:
- #11 
- #5

**Comment by yashu1wwww** [comment]
👉GitHub Live Profile Visits Count Followers Count Tool(Used Ai)
https://shorturl.at/jCPX3

**Comment by antonkomarev** [comment]
You've just made a wrapper around this service? How is it related to the AI then?

**Comment by yashu1wwww** [comment]
I just used ai tool kit called perplexity.ai to build all over World GitHub user live Followers Count & profile visits count and it's not clear in mobile device can you make responsive design
