### ISSUE TITLE
Profile viewed zeroed

### ISSUE THREAD

**Issue by berkealgul** [antonkomarev/github-profile-views-counter#50]
after the yesterdays issue my view count resetted. is anyone else experienced same issue?

**Comment by antonkomarev** [comment]
This issue is not related to the downtime. There is a case when two concurrent requests may overwrite counter value. But because detalization is stored in the separate file, we will be able to recount and restore these values.
I recommend you to use https://yhype.me, it does not have concurrent requests issue and have much more features which are not possible to implement in this project.

**Comment by berkealgul** [comment]
thank you for reply. How we should restore the previous count value?

**Comment by antonkomarev** [comment]
@berkealgul if you want to help, you could write script to count views in detalized file and write result in summary file. I will help with the review.
