### ISSUE TITLE
[Bug] Switching between tabs on profile page increases the profile view counter by 3

### ISSUE THREAD

**Issue by akash-rt** [antonkomarev/github-profile-views-counter#55]
On profile page, if you switch tab say from Overview to Repository and come back to Overview tab, you'll see counter of profile view is increased by 3. 

Not sure about the feasibility, but it should increase by one only.

**Comment by antonkomarev** [comment]
Each profile view page doesn't use any cache, so page loading increments the counter.

We don't know who was the original initiator of the request, we can only increase the counter when GitHub server message us.

This is because GitHub proxies all image URLs through the GitHub Camo service. The IP address and user agent in each request are always the same, they are replaced with Camo service ones.
