### ISSUE TITLE
There occurs a problem with the display of the icon

### ISSUE THREAD

**Issue by lim-yoona** [antonkomarev/github-profile-views-counter#79]
## Description
I have been using github-profile-views-counter to count my page views for a long time. Yesterday I discovered that there was an error in the icon display.

## Detail
<img width="524" alt="image" src="https://github.com/antonkomarev/github-profile-views-counter/assets/44336448/e3871766-5993-40fa-86c5-00381e653785">

## The code I use
```
<p align="center">
  <a href="https://github.com/lim-yoona">
    <img src="https://komarev.com/ghpvc/?username=limyoona&color=blue&style=flat)" />
  </a>
</p>
```
and using markdown code also has the same effect.

**Comment by antonkomarev** [comment]
Duplicate. Will notify about resolution here:
- #78

**Comment by igorskyflyer** [comment]
> ## The code I use
> ```
> <p align="center">
>   <a href="https://github.com/lim-yoona">
>     <img src="https://komarev.com/ghpvc/?username=limyoona&color=blue&style=flat)" />
>   </a>
> </p>
> ```
> 
> and using markdown code also has the same effect.

@lim-yoona

Sidenote: when the issue is resolved and you bring back the code, make sure to fix a typo in the URL.

I checked your README's commit history [01dea8067a2a5b4efe0364f1644ea39fd7350a0c](https://github.com/lim-yoona/lim-yoona/commit/01dea8067a2a5b4efe0364f1644ea39fd7350a0c), the `src` attribute of the `<img>` tag should be:

> https://komarev.com/ghpvc/?username=limyoona&color=blue&style=flat

and not

> https://komarev.com/ghpvc/?username=limyoona&color=blue&style=flat)

You have a redundant parenthesis at the end of the URL. 😉
