### ISSUE TITLE
Can I not count myself ? 

### ISSUE THREAD

**Issue by lix19937** [antonkomarev/github-profile-views-counter#93]

**Comment by antonkomarev** [comment]
Short answer: it is impossible.

Long read from FAQ:

**Why does the counter increase every time the page is reloaded?**
This is counter of profile views (page hits), not a counter of unique visitors. There is no way to get the username, browser user agent or IP address of the visitor because GitHub proxies all image URLs through the GitHub Camo service. In other words, we can only increment the counter for each request from the GitHub proxy server, we don't know who initiated it.

**Comment by lix19937** [comment]
@antonkomarev  Thanks !
